#!/usr/bin/env bash
# Script to install an nginx web-server on server
apt-get -y update
apt-get -y install nginx
touch /var/www/html/index.html
echo '<!DOCTYPE html>
<html>
        <body>
                <p>Hello World!</p>
        </body>
</html>' > /var/www/html/index.html
service nginx restart
