#!/usr/bin/env bash
# Set up load balancer
apt-get install -y software-properties-common
apt-get update
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 155770-web-01 54.82.180.60:80 check
   server 155770-web-02 54.160.97.8:80 check
EOF
service haproxy restart
